### ISSUE TITLE
suggestion about removing libdatachannel as a submodule

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/datachannel-wasm#10]
Hi paullouisageneau,

How do you think about removing libdatachannel as a submodule from this repository? A person using libdatachannel and datachannel-wasm together can add both of them as submodules and then add an if statement in their cmake code. As datachannel-wasm is a partial implementation of libdatachannel for wasm without actual code dependency, I think this can make this repository lighter! Versioning can be done by adding a line to the readme file or by adding a Version file.

This improvement would become visible when working with a forked version of libdatachannel with datachannel-wasm. Currently, this leads to having two copies of libdatachannel since there is a forked one and another one inside datachannel-wasm.

And thanks for your continuing work!

**Comment by paullouisageneau** [comment]
I like datachannel-wasm being platform agnostic, however I admit it could be more practical to separate libdatachannel. It doesn't make integration a lot more difficult.

**Comment by hanseuljun** [comment]
Thanks for being so acceptive to suggestions. I think since you have Convergence as an excellent example for people on how to use the wasm part of datachannel-wasm and libdatachannel together, removing as submodule won't hurt that much in this direction, but I also understand if you prefer the other direction since its just a submodule that can be ignored without having side effects more than allocating some disk space.
