### ISSUE TITLE
Usage of IceServer as a struct in Configuration

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/datachannel-wasm#16]
To support TURN, username and password needs to be provided. And for doing this, I think struct IceServer should be added and std::vector<IceServer> should be a member variable of Configuration instead of std::vector<std::string>. This will increase the compatibility of datachannel-wasm to the current version of libdatachannel.

I plan to do this, but first mentioning it here since the change won't be 100% backward compatible, though the difference would be trivial enough to catch up. Let me know if this is not what you want.

**Comment by paullouisageneau** [comment]
Indeed the support for TURN is currently missing. I think adding the same `IceServer` structure as libdatachannel makes sense!
