### ISSUE TITLE
About using stringToUTF8 instead of allocUTF8FromString in webrtc.js and websocket.js

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/datachannel-wasm#23]
How do you think about using stringToUTF8 from https://emscripten.org/docs/api_reference/preamble.js.html? In case you are okay with using stringToUTF8, as it is a part of emscripten, in effort to follow the herd to receive free updates (though this function is not something that is likely to change over time), I would like to try using stringToUTF8!

**Comment by paullouisageneau** [comment]
Actually, `allocUTF8FromString` is a helper function to allocate the memory with `malloc` and convert the string with `stringToUTF8`.

**Comment by hanseuljun** [comment]
Oh, you are right. I'm not sure why I haven't seen that. My bad haha
