### ISSUE TITLE
Native build not building

### ISSUE THREAD

**Issue by jacobfriedman** [paullouisageneau/datachannel-wasm#3]
Rebonjour! I'm trying to build the lowest-level datachannel I can to use the Prolog foreign interface/compiler... in attempting to build this subset for native after `cmake -B build-native`, in the directory 'build-native' the `make` doesn't yield anything.

I'm very new to the c/c++ build environment and would definitely try to troubleshoot if I knew more. Any help would be appreciated!

**Comment by paullouisageneau** [comment]
This is actually expected: when you build the project for a native target, cmake only links libdatachannel. The idea is that you only need to link `datachannel-wasm` from your multi-platform project, and the datachannel API will be exposed by the wrapper if you compile for wasm or by libdatachannel if you compile for native.

**Comment by jacobfriedman** [comment]
I see- thank you very much.
