### ISSUE TITLE
how to use? can i use this in some embed v8 env to support wrtc?

### ISSUE THREAD

**Issue by sixian** [paullouisageneau/datachannel-wasm#31]
can you provide a wasm file? and a demo?  thank you !

**Comment by paullouisageneau** [comment]
Hi, this project actually provides the reverse use case: it allows accessing an existing WebRTC JavaScript API from wasm code. It is meant for wasm code running in a browser.

**Comment by jimmywarting** [comment]
I would also like to see a demo and also a pre built wasm file so that i don't have to build or install any additional complicated emscripten stuff.

**Comment by paullouisageneau** [comment]
A pre-build wasm file does not make much sense, because the wrapper has to be linked statically by an external C++ project, which will built the wasm file.
