### ISSUE TITLE
WebSocket error unknown

### ISSUE THREAD

**Issue by jeffRTC** [paullouisageneau/datachannel-wasm#4]
Code,

```
#include "rtc/wasm-rtc.hpp"
#include <memory>
#include <iostream>


int main() {
    auto ws = std::make_shared<rtc::WebSocket>();

    ws->onError([](std::string s) {
        std::cout << "WebSocket error"
                  << s
                  << "\n";
    });

    ws->open("ws://whatever.com");

    return 0;
}
```

Compile with,

```
em++ main.cpp ^
C:/testPro/testPro/deps/datachannel-wasm/wasm/src/channel.cpp C:/testPro/testPro/deps/datachannel-wasm/wasm/src/datachannel.cpp ^
C:/testPro/testPro/deps/datachannel-wasm/wasm/src/peerconnection.cpp C:/testPro/testPro/deps/datachannel-wasm/wasm/src/websocket.cpp ^
-o testMe.js --bind -Oz -I C:/testPro/testPro -I C:\testPro\testPro\deps\datachannel-wasm\wasm\include ^
-I C:\testPro\testPro\deps\datachannel-wasm\wasm\include\rtc ^
--js-library C:/testPro/testPro/deps/datachannel-wasm/wasm/js/webrtc.js ^
--js-library C:/testPro/testPro/deps/datachannel-wasm/wasm/js/websocket.js ^
-lpthread ^
-s EXPORT_ALL=1 -std=c++1z  -s MODULARIZE=1 -g4 -s "EXPORT_NAME='testMe'" ^ 
-s DISABLE_EXCEPTION_CATCHING=0 -s ASYNCIFY=1 -s NO_EXIT_RUNTIME=1 -s WASM=1  ^ 
-s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap']" -s ALLOW_MEMORY_GROWTH=1 -DNDEBUG=1
```

Result,

`WebSocket error unknown
Uncaught 5279544
`

Real world app stack-trace,

![Screenshot_26](https://user-images.githubusercontent.com/74643784/100047684-faf76500-2e0a-11eb-8a15-3839f5b5cfac.png)

To debug the error, I've modified the ./wasm/websocket.js as follows,

```
		wsCreateWebSocket: function(pUrl) {
			var url = UTF8ToString(pUrl);
			console.log(pUrl)
			if(!window.WebSocket) return 0;
			return WEBSOCKET.registerWebSocket(new WebSocket(url));
		},
```
The function console log `5279128` and I have no idea why it console log a numeric type data.

**Comment by paullouisageneau** [comment]
The issue is that in your code, you open the WebSocket, then immediately return which destroys it. The API is asynchronous since the JavaScript one. If you wait for some time without returning immediately it should connect properly.

> The function console log 5279128 and I have no idea why it console log a numeric type data.

`pUrl` is actually a C pointer passed to Javascript, that's why it is a number. You need to log `url`, which is a string.

**Comment by jeffRTC** [comment]
But how would you wait?

I haven't found a method to wait. 

I tried with while(true) loop and that also didn't work, error was out instantly but browser halted due to high CPU usage

**Comment by paullouisageneau** [comment]
Oh yes sorry, you need to return from wasm code. You should actually put the `ws` smart point as a global variable to keep it alive. while you return to JavaScript.

**Comment by jeffRTC** [comment]
Global vars are really ugly. How did you used this on your game? Was it global vars?

I've looked but you've not used that. There were no signs of loop either other than the render loop

**Comment by jeffRTC** [comment]
Note that I compile with NO_EXIT_RUNTIME which should allow the WS callbacks to run  since NO_EXIT_RUNTIME doesn't run destructors.

**Comment by paullouisageneau** [comment]
Global variables are ugly in general, however they are necessary here to keep references between calls from Javascript. You can still organize everything cleanly. In fact, I use one global variable only in my game, here `engine` actually keeps everything alive, including game state:
https://github.com/paullouisageneau/convergence/blob/d8cdcdfc7e3237e7b1c164d3479be3c684a9f8e6/src/main.cpp#L34

The main loop is simulated with `emscripten_set_main_loop`:
https://github.com/paullouisageneau/convergence/blob/d8cdcdfc7e3237e7b1c164d3479be3c684a9f8e6/src/main.cpp#L46

`NO_EXIT_RUNTIME` is enabled by default and it does not do what you think it does, see https://emscripten.org/docs/getting_started/FAQ.html
> By default Emscripten sets EXIT_RUNTIME=0, which means that we don’t include code to shut down the runtime. That means that when main() exits, we don’t flush the stdio streams, or call the destructors of global C++ objects, or call atexit callbacks. This lets us emit smaller code by default, and is normally what you want on the web: even though main() exited, you may have something asynchronous happening later that you want to execute.

The point is only not to destroy global objects. It means destructors of objects going out of scope are still called, even in the main function scope.

**Comment by jeffRTC** [comment]
The thing is I need to run your websoocket abstraction in pThreads and when we use shared pointer I guess it use main thread.

**Comment by jeffRTC** [comment]
Hmm there is a keyword called thread_local but not sure whether it would work or not

**Comment by paullouisageneau** [comment]
You could set a global shared pointer from a thread. 

However, multithreading in wasm is an extremely recent functionality that won't be supported everywhere. Note you might need to configure emscripten to output wasm threads rather than converting them to dummy code if you haven't already.

Also, parts of the wrapper might not work because it calls the Javascript API under the hood. For instance, PeerConnection is not accessible to WebWorkers so I think it may also not be accessible to wasm threads. 

My point here is that using threads will cause a lot of issues.

**Comment by jeffRTC** [comment]
So I got the Websocket part fixed by using what you suggested. Now, however; the RTC part seems broken. 

```
std::shared_ptr<rtc::PeerConnection>
RTCTransport::createPeerConnection(const rtc::Configuration &config, std::weak_ptr<rtc::WebSocket> ws, std::string id)
{
    auto pc = std::make_shared<rtc::PeerConnection>(config);

    std::cout << "DEBUG: createPeerConnection has been called" << "\n";

    pc->onLocalDescription([ws, id](rtc::Description description) {
        nlohmann::json message = {{"id", id}, {"type", description.typeString()}, {"sdp", std::string(description)}};

        auto socket = ws.lock();

        if (socket)
        {
            socket->send(message.dump());
        }
    });

    pc->onLocalCandidate([ws, id](rtc::Candidate candidate) {
        nlohmann::json message = {{"id", id},
                                  {"type", "candidate"},
                                  {"candidate", std::string(candidate)},
                                  {"sdpMid", candidate.mid()}};

        auto socket = ws.lock();

        if (socket)
        {
            socket->send(message.dump());
        }
    });

    peerConnectionMap.emplace(id, pc);
    return pc;
}
```


  ```
 ws->onOpen([&]() {
        std::cout << "WebSocket connected, signaling ready"
                  << "\n";   /// THIS PRINTS

        auto pc = createPeerConnection(config, ws, localID); /// BUT THIS FAILS
        auto dc = pc->createDataChannel(localID);

        dc->onOpen([dc](){
            std::cout << "Data Channel is ready" << "\n";
            dc->send("Heyyyyyyy from Client");
        });
```

The call to createPeerConnection  function in same class fails!

**Comment by paullouisageneau** [comment]
What do you mean by "it fails"?

**Comment by paullouisageneau** [comment]
Note you have the same problem as before, `pc` needs to be stored somewhere otherwise it will be destroyed immediately when leaving the scope.

**Comment by jeffRTC** [comment]
Duh!

WebWorkers only support QUIC based Data Channel

https://github.com/paullouisageneau/libdatachannel/issues/111

but your lib has not added that yet

**Comment by paullouisageneau** [comment]
There is virtually no browser support for WebRTC with QUIC for now. `RTCQuicTransport` is actually a whole different stack and a whole new API replacing `PeerConnection` and ataChannel`. As of today it's only available on recent Chromium with a developper flag enabled, and documentation is really lacking, I have only seen an ORTC draft published last month. 

Don't expect this to be available soon, sadly it'll take some time.

**Comment by jeffRTC** [comment]
Fine, I will use in single thread for now. I guess all will be okay.

**Comment by jeffRTC** [comment]
I made a global var called `std::shared_ptr<rtc::PeerConnection> pc;` and the code now looks like this,


```
ws->onOpen([&]() {
      std::cout << "WebSocket connected, signaling ready"
                << "\n";   /// THIS PRINTS

      pc = createPeerConnection(config, ws, localID); /// BUT THIS FAILS
      auto dc = pc->createDataChannel(localID);

      dc->onOpen([dc](){
          std::cout << "Data Channel is ready" << "\n";
          dc->send("Heyyyyyyy from Client");
      });
```

But the call to function fails. JS console output again a numeric type value Uncaught 5281056

**Comment by paullouisageneau** [comment]
It means there is an uncaught exception, you should add a try/catch block inside the onOpen callback to display it. Also, you should also store the DataChannel somewhere also.

**Comment by jeffRTC** [comment]
But why store DC somewhere since WS already stored somewhere?

In my non-wasm code, I didn't do that.

**Comment by paullouisageneau** [comment]
Here it will work by chance because the DataChannel onOpen callback will keep a reference. In practice, it's better to pass a weak pointer to allow the DataChannel destruction and prevent a memory leak.

**Comment by jeffRTC** [comment]
I printed out the error.

Error: allocator<T>::allocate(size_t n) 'n' exceeds maximum supported size

**Comment by paullouisageneau** [comment]
Some argument is probably corrupt. How is `config` allocated?

**Comment by jeffRTC** [comment]
Like this

```
void RTCTransport::initialize(std::string &WebSocketEndpoint, std::vector<std::string> &iceServers)
{
    //"stun:stun.services.mozilla.com:3478"
    for (const auto &i : iceServers)
    {
        config.iceServers.emplace_back(i);
    }
```
config is equals to  `rtc::Configuration config;` in RTCTransport class

**Comment by paullouisageneau** [comment]
OK, and is the `RTCTransport` instance a global variable?

**Comment by jeffRTC** [comment]
No.

```
int main() {
    RTCTransport network;

    std::string endpoint = "ws://whatever.com";

    std::vector<std::string> ICEServers;

    ICEServers.push_back("stun:stun.services.mozilla.com:3478");

    network.initialize(endpoint, ICEServers);
}
```

**Comment by paullouisageneau** [comment]
Well that's your problem, and it's always the same problem. At the end of main, `network` will be destroyed, so when the onOpen callback is called, it does not exist anymore.

You must not use things allocated in the main function scope in callbacks, you have to allocate them globally.

**Comment by jeffRTC** [comment]
That seems fixed but now getting this error

Error: WebSocket string messages are not supported

**Comment by paullouisageneau** [comment]
Oh yes, this is something I need to add to the wrapper, I only use binary messages in my game. For now you can send the messages as `rtc::binary`.

**Comment by jeffRTC** [comment]
How to convert string to rtc::binary type?

**Comment by jeffRTC** [comment]
Perhaps from nlohman directly

**Comment by paullouisageneau** [comment]
You can do something like: 
```
std::string str = json.dump();
auto *data = reinterpret_cast<rtc::byte*>(str.data());
socket->send(rtc::binary(data, data+str.size()));
```
and the other way around:
```
auto *data = reinterpret_cast<char*>(bin.data());
std::string str(data, data + bin.size());
```

I'll add string message support when I get the time, it shouldn't be too complex.

**Comment by paullouisageneau** [comment]
@jeffRTC I added support for string messages in https://github.com/paullouisageneau/datachannel-wasm/commit/90fdaaab3d9d0ca1449e1d926fa2e13fec621b78

**Comment by jeffRTC** [comment]
Thank you for this. Everything works now!
