### ISSUE TITLE
ServiceWorker datachannel-wasm <=> window native datachannel

### ISSUE THREAD

**Issue by guest271314** [paullouisageneau/datachannel-wasm#40]
Can this library create a WASM datachannel in a `ServiceWorker` and communicate with `window`?

In the source code `window` is referenced. `ServiceWorker` does not have a `window`. `globalThis` can be substituted for `window` below if in fact [datachannel-wasm](https://github.com/paullouisageneau/datachannel-wasm) can be created in a `ServiceWorker` (or Worker).

https://github.com/paullouisageneau/datachannel-wasm/blob/bb1da1b7b1f9d4555aaf097d606bcad20eed7245/wasm/js/webrtc.js#L152

**Comment by paullouisageneau** [comment]
The WebRTC API is not exposed to Service Workers in browsers so sadly datachannel-wasm won't work in a Service Worker.

**Comment by guest271314** [comment]
Ah, I was thinking you defined WebRTC in WASM, thus exposed WebRTC in any context. This https://rustwasm.github.io/wasm-bindgen/examples/webrtc_datachannel.html must not do that either.

**Comment by paullouisageneau** [comment]
> Ah, I was thinking you defined WebRTC in WASM, thus exposed WebRTC in any context. This https://rustwasm.github.io/wasm-bindgen/examples/webrtc_datachannel.html must not do that either.

In browser contexts you can't implement a custom WebRTC stack as there are no lower-level network API, so you actually need to wrap the existing JS API. That's indeed what Rust bindings also do.
