### ISSUE TITLE
Match libdatachannel's reliability.hpp

### ISSUE THREAD

**Issue by golgirihm** [paullouisageneau/datachannel-wasm#54]
Hello!

First off, thank you for the wonderful libraries. They are incredibly useful!

I have a project that uses [libdatachannel](https://github.com/paullouisageneau/libdatachannel) in conjuction with [datachannel-wasm](https://github.com/paullouisageneau/datachannel-wasm). Recently, I pulled to a newer version of [libdatachannel](https://github.com/paullouisageneau/libdatachannel), and found that I had a build error due to the [refactor of the data channel reliability API (#1031)](https://github.com/paullouisageneau/libdatachannel/pull/1031). I was able to fix this error in one part of my project (the native app), but it breaks the other part of the project (the web app).

Is there a plan to update [datachannel-wasm](https://github.com/paullouisageneau/datachannel-wasm) to match the `reliability` in the latest [libdatachannel](https://github.com/paullouisageneau/libdatachannel)?

**Comment by paullouisageneau** [comment]
This is done in https://github.com/paullouisageneau/datachannel-wasm/pull/51 which is not merged, I was waiting for the new version of libdatachannel to be released.

I'll merge it now!
