### ISSUE TITLE
a wish about the license

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/datachannel-wasm#7]
Hello Paul-Louis,

First of all, I really really appreciate the help I've received already so this is more like a wish, nothing more than that.

Currently, this repository is under AGPL. As I have very much enjoyed your other libraries, I wanted to ask whether it would be possible to let this repository stay under LGPL as your other libraries.

If that is possible, I can promise
1. making this repository to work with Emscripten 2.0 (currently there are some minor issues, e.g., dynCall_sig() functions got removed recently)
and
2. try adding some rudimentary support for media transports.

Of course I am working on them because of my work, so I am not doing some humanitarian work here, just hoping them to give you a second thought!

**Comment by paullouisageneau** [comment]
Hello!

> Currently, this repository is under AGPL. As I have very much enjoyed your other libraries, I wanted to ask whether it would be possible to let this repository stay under LGPL as your other libraries.

The code is under AGPL because the project it is extracted from was. I guess it would make sense to have it under the same license as libdatachannel.
 
> If that is possible, I can promise
> 
>     1. making this repository to work with Emscripten 2.0 (currently there are some minor issues, e.g., dynCall_sig() functions got removed recently)

Yeah, it seems I have changed these calls more than twice already. People working on emscripten sure love to break the API often!

>        and
> 
>     2. try adding some rudimentary support for media transports.

I'm a bit doubtful about this for now. How do you picture the API? The main issue is that the JavaScript API is high-level and libdatachannel is way lower level.

> Of course I am working on them because of my work, so I am not doing some humanitarian work here, just hoping them to give you a second thought!

Your contributions are still welcome!

**Comment by paullouisageneau** [comment]
The code is re-licensed to LGPLv2 on `master`.

**Comment by hanseuljun** [comment]
Thank you so much!! I'm a total newbie to emscripten, so can't say much but I also hope they slow down eventually because this deprecation made me question myself at least for like an hour haha. About media transports, as I feel a pretty strong urge to make this happen, I'll try pretty hard to come up with a feasible approach!

**Comment by hanseuljun** [comment]
Now I finally really understand how impossible it would be to support libdatachannel's media API through the JS API. Seems like I can't even send a custom message through a JS media track. Sorry for not keeping my words...

**Comment by paullouisageneau** [comment]
Ha ha no problem, it seems to me that it would be very hard to achieve. I think the only way would be replicating the full `MediaDevices` API first...
